name: CI
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix: { python: ['3.10','3.11','3.12'] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python }} }
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt || true
      - run: pip install -r requirements-dev.txt
      - run: ruff check .
      - run: black --check .
      - run: python -m compileall -q -f .
      - name: Tests (headless)
        env: { SDL_VIDEODRIVER: dummy }
        run: pytest -q

  windows:
    runs-on: windows-latest
    strategy:
      matrix: { python: ['3.10','3.11','3.12'] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python }} }
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt || powershell -c "exit 0"
      - run: pip install -r requirements-dev.txt
      - run: python -m ruff check .
      - run: python -m black --check .
      - run: python -m compileall -q -f .
      - name: Tests (headless)
        shell: bash
        run: SDL_VIDEODRIVER=dummy pytest -q

  all_green:
    runs-on: ubuntu-latest
    needs: [ubuntu, windows]
    steps:
      - run: echo "All required checks passed."
